# Generated by Django 5.2.4 on 2025-07-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nirfranking',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='fees_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fees per year in Lakhs (e.g., 1.5 for 1.5 Lakhs)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nirfranking',
            name='engineering_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nirfranking',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus_area_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='official_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ownership_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Deemed', 'Deemed University/Deemed to be University'), ('Government-Aided', 'Government-Aided')], default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='intake_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nirfranking',
            name='engineering_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nirfranking',
            name='overall_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nirfranking',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='average_package_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average package in Lakhs per annum', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='highest_package_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Highest package in Lakhs per annum', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='median_package_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Median package in Lakhs per annum', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='placement_percentage',
            field=models.FloatField(blank=True, help_text='Percentage of students placed (e.g., 90.5 for 90.5%)', null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='students_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='total_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementdata',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='JEECutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., OPEN, OBC-NCL, SC, ST, EWS', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, help_text='e.g., Gender-Neutral, Female-only', max_length=10, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jee_cutoffs', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course')),
            ],
            options={
                'ordering': ['-year', 'course__name', 'closing_rank'],
                'unique_together': {('college', 'course', 'year', 'category', 'gender')},
            },
        ),
    ]
